const AUTOSTART=()=>{
const DATA=`OPERATINGSYSTEM();AUTORUN();BODY();ZOOM();HOSTINGUPDATER();INSPECTION();HOSTINGINSTALLER();URLCOLLECTOR();
`;
localStorage.setItem('AUTOSTART',DATA);
};
export{AUTOSTART};